### ISSUE TITLE
Windows named pipe error - docker log from python container

### ISSUE THREAD

**Issue by baram204** [baram204/usedCarPriceExpectationWithML#1]
**ENV** :

win10, Intellij idea default terminal pane.

**REPRODUCE** :

```
C:\Users\baram204\IdeaProjects\usedCarPriceExpectationWithML\docker>docker-compose up
ERRORERROR: Windows named pipe error: 횁철횁짚쨉훻 훴횆흺훿흺쨩 훯흟흺쨩 캭철 컁힂?흺쨈훿쨈큽. (code: 2)
Traceback (most recent call last):
  File "logging\__init__.py", line 884, in emit
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Logged from file errors.py, line 79
```

**Comment by baram204** [comment]
It's from python error. Docker catch containers all stdout signal. 
[ref](https://docs.docker.com/v17.09/engine/admin/logging/view_container_logs/)

so, It's python error.

**Comment by baram204** [comment]
I tried windows cmd prompt. and It's woking.

dif between two :

1.  utf-8 character oupt. - win 10 cmd prints well.
2. setenv.bat - wind 10

**Comment by baram204** [comment]
2 is right. tried it inside intellij term. woking.

but, installij doesn't allow parameter on default ternimal.

so make external run tool.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/206815635-How-can-I-call-out-Windows-CMD-and-autocd-into-the-project-path-from-intellij-
